name: ondevice
packages:
  - apps/**
  - packages/**

scripts:
  get:
    run: melos exec -- flutter pub get
    description: pub get across all packages
  analyze:
    run: melos exec -- flutter analyze
    description: analyze across all packages
  test:
    run: melos exec -- flutter test
    description: test across all packages
  clean:
    run: melos exec -- flutter clean
    description: clean across all packages
